hosts:
  # windows1:
  #   type: windows
  #   hostname: 192.168.1.102
  #   username: administrator
  #   password: admin123
  # linux1:
  #   type: linux
  #   hostname: 192.168.1.103
  #   auth_method: private_key
  #   username: root
  #   key_path: /path/to/private/key
