hosts:
  linux1:
    type: OS (Linux or Windows)
    hostname: IP
    auth_method: password or private_key
    username: username
    password: password
  linux2:
    type: OS (Linux or Windows)
    hostname: IP
    auth_method: password or private_key
    username: username
    password: password
  # windows1:
  #   type: windows or Linux
  #   hostname: IP
  #   username: username
  #   password: password
  # linux1:
  #   type: linux
  #   hostname: IP
  #   auth_method: private_key
  #   username: username
  #   key_path: /path/to/private/key
