hosts:
  linux1:
    type: linux #kali1
    hostname: hostname
    auth_method: password
    username: kali 
    password: kali
  linux2:
    type: linux #kali2
    hostname: hostname
    auth_method: password
    username: kali
    password: kali
  # windows1:
  #   type: windows
  #   hostname: IP
  #   username: username
  #   password: password
  # linux1:
  #   type: linux
  #   hostname: IP
  #   auth_method: private_key
  #   username: username
  #   key_path: /path/to/private/key
